# Check for updates.
check_for_update: true

banned_block_break: "all"

banned_block_inventory: "all"

banned_entity_inventory: "all"

banned_entity_spawn: "all"

banned_item_drop: "all"

banned_right_click: "all"
