# Check for updates.
checkForUpdate: true

# Prevent players from interacting with block based inventories (i.e. Chests, Dispensers, etc.).
# Use materials or it won't register
# Use {} to allow all blocks and items.
noBlockBasedInventory:
  dispenser:
    - 0
  chest:
    - 0
  furnace:
    - 0
  burning_furnace:
    - 0
  monster_eggs:
    - 0
  enchantment_table:
    - 0
  brewing_stand:
    - 0
  ender_chest:
    - 0
  beacon:
    - 0
  anvil:
    - 0
    - 1
    - 2
  trapped_chest:
    - 0
  hopper:
    - 0
  dropper:
    - 0
  
# Prevent players from interacting with entity based inventories (i.e. Storage minecart, Villagers)
# To enable all entity based mobs, use - none.
noEntityBasedInventory:
  - minecart_chest
  - minecart_hopper
  - villager
  
# Prevent blocks/items from being dropped. Use materials or it won't register.
# Use {} to allow all blocks and items.
noDrop:
  bedrock:
    - 0
  water:
    - 0
  stationary_water:
    - 0
  lava:
    - 0
  stationary_lava:
    - 0
  tnt:
    - 0
  fire:
    - 0
  mob_spawner:
    - 0
  monster_eggs: # Silverfish Blocks
    - all
  water_bucket:
    - 0
  lava_bucket:
    - 0
  potion:
    - all

# Prevent block placement. Use materials or it won't register.
# Use {} to allow all blocks.
noPlace:
  bedrock:
    - 0
  water:
    - 0
  stationary_water:
    - 0
  lava:
    - 0
  stationary_lava:
    - 0
  tnt:
    - 0
  fire:
    - 0
  mob_spawner:
    - 0
  monster_eggs: # Silverfish Blocks
    - all
  water_bucket:
    - 0
  lava_bucket:
    - 0
  potion:
    - all
  
# Prevent the use of spawn eggs.
# To enable all mobs. Simply put - none.
noSpawn:
  - all

# Prevent items from being thrown. (i.e. Right click with a chicken egg.)
# Use materials or it won't register.
# Use {} to allow all throwables.
noThrow:
  snow_ball:
    - 0
  egg:
    - 0
  potion:
    - 0
  exp_bottle:
    - 0

# Prevent bucket water/lava bucket and TNT Minecart usage.
blockWaterBucket: true
blockLavaBucket: true
blockTNTMinecart: true