name: ControlCreativeMode
main: musician101.controlcreativemode.spigot.SpigotCCM
version: ${project.version}
description: Change from creative and survival
authors: [boardingamer, Musician101]
maintainer: Musician101

commands:
    ccm:
        description: Commands for the plugin.
        aliases: [ccm]
