# Set which blocks can't be broken.
banned_block_break: "all"

# Set which block based inventories can't be accessed.
# i.e. Chests, Anvils, etc.
banned_block_inventory: "all"

# Set which entity based inventories can't be accessed.
# i.e. Villagers
banned_entity_inventory: "all"

# Set which entities can't be spawned through the use of Spawn Eggs.
banned_entity_spawn: "all"

# Set which items can't be dropped.
banned_item_drop: "all"

# Set which items can't be right-clicked.
# This will prevent block placing, throwing snowballs and splash potions, and bows from functioning.
banned_right_click: "all"
