name: ControlCreativeMode
main: io.musician101.controlcreativemode.spigot.SpigotCCM
version: \${project.version}
description: Change from creative and survival
authors: [boardingamer, Musician101]
maintainer: Musician101
softdepend: [MusicianLibrary-Spigot]

commands:
    ccm:
        description: Commands for the plugin.
        aliases: [ccm]
