# Check for updates.
checkForUpdate: true

# Prevent players from interacting with block based inventories (i.e. Chests, Dispensers, etc.).
# Use materials or it won't register
# Use {} to allow all blocks and items.
noBlockBasedInventory:
  - dispenser
  - chest
  - furnace
  - burning_furnace
  - monster_eggs
  - enchantment_table
  - brewing_stand
  - ender_chest
  - beacon
  - anvil
  - trapped_chest
  - hopper
  - dropper
  
# Prevent players from interacting with entity based inventories (i.e. Storage minecart, Villagers)
# To enable all entity based mobs, use - none.
noEntityBasedInventory:
  - minecart_chest
  - minecart_hopper
  - villager
  
# Prevent blocks/items from being dropped. Use materials or it won't register.
# Use {} to allow all blocks and items.
noDrop:
  - bedrock
  - water
  - stationary_water
  - lava
  - stationary_lava
  - tnt
  - fire
  - mob_spawner
  - monster_eggs # Silverfish Blocks
  - water_bucket
  - lava_bucket
  - potion

# Prevent block placement. Use materials or it won't register.
# Use {} to allow all blocks.
noPlace:
  - bedrock
  - water
  - stationary_water
  - lava
  - stationary_lava
  - tnt
  - fire
  - mob_spawner
  - monster_eggs # Silverfish Blocks
  
# Prevent the use of spawn eggs.
# To enable all mobs. Simply put - none.
noSpawn:
  - creeper
  - skeleton
  - spider
  - zombie
  - slime
  - ghast
  - zombiePigman
  - enderman
  - caveSpider
  - silverfish
  - blaze
  - magmaCube
  - bat
  - witch
  - pig
  - sheep
  - cow
  - chicken
  - squid
  - wolf
  - mooshroom
  - snowGolem
  - ocelot
  - ironGolem
  - villager

# Prevent items from being thrown. (i.e. Right click with a chicken egg.)
# Use materials or it won't register.
# Use {} to allow all throwables.
noThrow:
  - snow_ball
  - egg
  - potion
  - exp_bottle

# Prevent bucket water/lava bucket and TNT Minecart usage.
blockWaterBucket: true
blockLavaBucket: true
blockTNTMinecart: true